# Generated by Django 4.1.5 on 2023-11-28 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_alter_follows_candidate_id_and_more'),
        ('powered_by', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poweredbyrequest',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
    ]
