# Generated by Django 4.1.5 on 2023-11-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powered_by', '0002_poweredbyrequest_company_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poweredbyrequest',
            old_name='response',
            new_name='api_response',
        ),
        migrations.AddField(
            model_name='poweredbyrequest',
            name='processed_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poweredbyrequestattachment',
            name='processing_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
