# Generated by Django 4.1.5 on 2023-12-01 08:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0012_candidateexternalid'),
        ('powered_by', '0003_rename_response_poweredbyrequest_api_response_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoweredByWebhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Attachment Request Id')),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('payload', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'powered_by_webhook',
            },
        ),
        migrations.AddField(
            model_name='poweredbyrequestattachment',
            name='candidate_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='candidate.candidate'),
        ),
    ]
