# Generated by Django 4.1.5 on 2023-12-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powered_by', '0004_poweredbywebhook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poweredbywebhook',
            name='payload',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
