# Generated by Django 4.1.5 on 2023-12-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powered_by', '0005_alter_poweredbywebhook_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='poweredbyrequestattachment',
            name='openai_stats',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
