# Generated by Django 4.1.5 on 2023-12-19 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powered_by', '0006_poweredbyrequestattachment_openai_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='poweredbywebhook',
            name='saving_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
