# Generated by Django 4.1.5 on 2023-12-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powered_by', '0007_poweredbywebhook_saving_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='poweredbyrequest',
            name='records_used',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
