# Generated by Django 4.1.5 on 2023-12-28 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('powered_by', '0008_poweredbyrequest_records_used'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poweredbyrequest',
            old_name='records_used',
            new_name='credits_used',
        ),
    ]
