# Generated by Django 4.1.5 on 2023-12-29 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powered_by', '0009_rename_records_used_poweredbyrequest_credits_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='poweredbyrequest',
            name='processing_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
