# Generated by Django 4.1.5 on 2024-01-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powered_by', '0010_poweredbyrequest_processing_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poweredbyrequest',
            name='processing_time',
        ),
        migrations.AddField(
            model_name='poweredbyrequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
