# Generated by Django 4.1.5 on 2024-01-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powered_by', '0011_remove_poweredbyrequest_processing_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poweredbyrequest',
            name='model',
            field=models.CharField(default='sd_v4', max_length=255),
        ),
    ]
