# Generated by Django 4.1.5 on 2025-03-12 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('powered_by', '0012_poweredbyrequest_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='poweredbyrequestattachment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
