# Generated by Django 4.1.5 on 2023-11-24 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genai_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidatemaster',
            options={},
        ),
        migrations.AlterModelTable(
            name='candidatemaster',
            table='candidate_master',
        ),
    ]
