# Generated by Django 4.1.5 on 2023-12-04 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genai_profile', '0002_alter_candidatemaster_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CandidateMaster',
        ),
    ]
