# Generated by Django 4.1.5 on 2023-12-04 11:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate', '0013_candidate_ai_candidate_id'),
        ('genai_profile', '0003_delete_candidatemaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenProfileProcess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Candidate Process Id')),
                ('status', models.CharField(blank=True, choices=[('pending', 'pending'), ('in_progress', 'in_progress'), ('success', 'success')], max_length=100, null=True)),
                ('gen_candidate_id', models.UUIDField(default=uuid.uuid4, null=True, verbose_name='Candidate GenProfile Id')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate')),
            ],
            options={
                'db_table': 'gen_profile_process',
            },
        ),
    ]
