# Generated by Django 4.1.5 on 2023-12-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genai_profile', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genprofileprocess',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('in_progress', 'in_progress'), ('already_generated', 'already_generated'), ('success', 'success')], max_length=100, null=True),
        ),
    ]
