# Generated by Django 4.1.5 on 2023-12-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genai_profile', '0005_alter_genprofileprocess_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genprofileprocess',
            name='gen_candidate_id',
            field=models.UUIDField(null=True, verbose_name='Candidate GenProfile Id'),
        ),
    ]
