# Generated by Django 4.1.5 on 2024-01-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genai_profile', '0006_alter_genprofileprocess_gen_candidate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genprofileprocess',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('in_progress', 'in_progress'), ('already_generated', 'already_generated'), ('success', 'success'), ('failed', 'failed')], max_length=100, null=True),
        ),
    ]
