# Generated by Django 4.1.5 on 2023-12-26 07:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job_posting', '0015_alter_jobpostingtemplate_industry_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainedTitle',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Trained Title ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_posting_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_posting.jobposting')),
            ],
            options={
                'db_table': 'trained_title',
            },
        ),
    ]
