# Generated by Django 4.1.5 on 2023-12-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainedtitle',
            name='model_version',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='trainedtitle',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'active'), ('inactive', 'inactive')], max_length=50, null=True),
        ),
    ]
