# Generated by Django 4.1.5 on 2024-01-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_training', '0002_trainedtitle_model_version_trainedtitle_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainedtitle',
            name='model_version',
        ),
        migrations.AddField(
            model_name='trainedtitle',
            name='major_version',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='trainedtitle',
            name='minor_version',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='trainedtitle',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'active'), ('inactive', 'inactive'), ('training_failed', 'training_failed')], max_length=50, null=True),
        ),
    ]
