# Generated by Django 4.1.5 on 2024-01-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_training', '0003_remove_trainedtitle_model_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainedtitle',
            name='major_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
