# Generated by Django 4.1.5 on 2024-01-03 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_training', '0004_alter_trainedtitle_major_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainedtitle',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trainedtitle',
            name='major_version',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainedtitle',
            name='minor_version',
            field=models.IntegerField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='trainedtitle',
            name='status',
            field=models.CharField(blank=True, choices=[('queued', 'queued'), ('completed', 'completed'), ('failed', 'failed')], max_length=50, null=True),
        ),
    ]
