# Generated by Django 4.1.5 on 2024-01-03 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_training', '0005_trainedtitle_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainedtitle',
            name='minor_version',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
