# Generated by Django 4.1.5 on 2024-01-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_training', '0006_alter_trainedtitle_minor_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainedtitle',
            name='model_s3_path',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
