# Generated by Django 4.1.5 on 2024-01-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_training', '0007_trainedtitle_model_s3_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainedtitle',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('queued', 'queued'), ('completed', 'completed'), ('failed', 'failed')], max_length=50, null=True),
        ),
    ]
