# Generated by Django 4.1.5 on 2023-02-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('employer', 'employer'), ('job_seeker', 'job_seeker'), ('admin', 'admin')], max_length=100, null=True),
        ),
    ]
