# Generated by Django 4.1.5 on 2023-05-11 13:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(default='', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='otp_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
