# Generated by Django 4.1.5 on 2023-05-12 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_otp_user_otp_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='otp_timestamp',
            new_name='otp_generated_at',
        ),
    ]
