# Generated by Django 4.1.5 on 2023-06-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_otp_timestamp_user_otp_generated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.TextField(blank=True, null=True),
        ),
    ]
