# Generated by Django 4.1.5 on 2023-09-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
