# Generated by Django 4.1.5 on 2023-09-07 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_company_deleted_at_follows_deleted_at_and_more'),
        ('accounts', '0011_user_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='location_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.location'),
        ),
    ]
