# Generated by Django 4.1.5 on 2024-04-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_user_location_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
