# Generated by Django 4.1.5 on 2023-03-23 09:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_alter_candidate_status'),
        ('job_posting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPostingCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Job Posting Candidate ID')),
                ('published', models.BooleanField(default=False)),
                ('hiring_stage', models.CharField(blank=True, max_length=100, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='candidate.candidate')),
                ('job_posting_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='job_posting.jobposting')),
            ],
            options={
                'db_table': 'job_posting_candidate',
            },
        ),
        migrations.CreateModel(
            name='JobPostingCandidateSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Job Posting Candidate Skill ID')),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate_skill_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='candidate.candidateskill')),
                ('job_posting_candidate_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='job_posting.jobpostingcandidate')),
            ],
            options={
                'db_table': 'job_posting_candidate_skill',
            },
        ),
    ]
