# Generated by Django 4.1.5 on 2023-04-06 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidate', '0002_alter_candidate_status'),
        ('company', '0002_subscription'),
        ('job_posting', '0002_jobpostingcandidate_jobpostingcandidateskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPostingReveals',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Job Posting Reveal ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='candidate.candidate')),
                ('job_posting_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='job_posting.jobposting')),
                ('revealed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='candidate_revealed_by', to=settings.AUTH_USER_MODEL)),
                ('subscription_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='company.subscription')),
            ],
            options={
                'db_table': 'job_posting_reveals',
            },
        ),
    ]
