# Generated by Django 4.1.5 on 2023-07-03 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_kanbanboard'),
        ('job_posting', '0004_alter_skill_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpostingcandidate',
            name='hiring_stage',
        ),
        migrations.AddField(
            model_name='jobpostingcandidate',
            name='hiring_stage_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='company.kanbanboard'),
        ),
    ]
