# Generated by Django 4.1.5 on 2023-07-27 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0005_remove_jobpostingcandidate_hiring_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='remote_type',
            field=models.CharField(blank=True, choices=[('state', 'state'), ('country', 'country'), ('any_region', 'any_region')], max_length=100, null=True),
        ),
    ]
