# Generated by Django 4.1.5 on 2023-09-07 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_alter_follows_candidate_id_and_more'),
        ('candidate', '0011_alter_candidateskill_skill_id_and_more'),
        ('job_posting', '0007_jobposting_deleted_at_jobpostingcandidate_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='location_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.location'),
        ),
        migrations.AlterField(
            model_name='jobpostingcandidate',
            name='candidate_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate'),
        ),
        migrations.AlterField(
            model_name='jobpostingcandidate',
            name='hiring_stage_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.kanbanboard'),
        ),
        migrations.AlterField(
            model_name='jobpostingcandidate',
            name='job_posting_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_posting.jobposting'),
        ),
        migrations.AlterField(
            model_name='jobpostingcandidateskill',
            name='candidate_skill_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='candidate.candidateskill'),
        ),
        migrations.AlterField(
            model_name='jobpostingcandidateskill',
            name='job_posting_candidate_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_posting.jobpostingcandidate'),
        ),
        migrations.AlterField(
            model_name='jobpostingreveals',
            name='candidate_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate'),
        ),
        migrations.AlterField(
            model_name='jobpostingreveals',
            name='job_posting_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_posting.jobposting'),
        ),
        migrations.AlterField(
            model_name='jobpostingskill',
            name='job_posting_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_posting.jobposting'),
        ),
    ]
