# Generated by Django 4.1.5 on 2023-09-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0008_alter_jobposting_location_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='source',
            field=models.CharField(blank=True, choices=[('adwerks', 'adwerks'), ('ats', 'ats'), ('portal', 'portal')], default='portal', max_length=100),
        ),
    ]
