# Generated by Django 4.1.5 on 2023-10-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0009_jobposting_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='zip',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
