# Generated by Django 4.1.5 on 2023-10-10 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0010_jobposting_city_jobposting_country_jobposting_state_and_more'),
        ('job_posting', '0010_jobpostingcandidateskill_skill_name'),
    ]

    operations = [
    ]
