# Generated by Django 4.1.5 on 2023-10-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0011_merge_20231010_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='minimum_match',
            field=models.BigIntegerField(default=35),
        ),
    ]
