# Generated by Django 4.1.5 on 2023-12-13 06:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_alter_follows_candidate_id_and_more'),
        ('job_posting', '0012_jobposting_external_id_jobposting_minimum_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPostingTemplate',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Job Posting Reveal ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('skill', models.TextField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('industry_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='company.industry')),
            ],
            options={
                'db_table': 'job_posting_template',
            },
        ),
    ]
