# Generated by Django 4.1.5 on 2023-12-13 07:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0013_jobpostingtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpostingtemplate',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Job Posting Template ID'),
        ),
    ]
