# Generated by Django 4.1.5 on 2023-12-13 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_alter_follows_candidate_id_and_more'),
        ('job_posting', '0014_alter_jobpostingtemplate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpostingtemplate',
            name='industry_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='company.industry'),
        ),
        migrations.AlterField(
            model_name='jobpostingtemplate',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
