# Generated by Django 4.1.5 on 2024-01-03 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_alter_follows_candidate_id_and_more'),
        ('job_posting', '0015_alter_jobpostingtemplate_industry_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostingtemplate',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
    ]
