# Generated by Django 4.1.5 on 2024-03-20 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job_posting', '0016_jobpostingtemplate_company_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherCandidates',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Other Candidates ID')),
                ('key', models.TextField()),
                ('error', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='other_candidates_created_by', to=settings.AUTH_USER_MODEL)),
                ('job_posting_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='job_posting.jobposting')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='other_candidates_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'other_candidates',
            },
        ),
    ]
