# Generated by Django 4.1.5 on 2024-03-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0017_othercandidates'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostingcandidate',
            name='source',
            field=models.CharField(blank=True, choices=[('other', 'other'), ('applied', 'applied'), ('startdate', 'startdate')], default='startdate', max_length=255, null=True),
        ),
    ]
