# Generated by Django 4.1.5 on 2024-04-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0018_jobpostingcandidate_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='othercandidates',
            name='failed',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='othercandidates',
            name='inserted',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='othercandidates',
            name='sent',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
