# Generated by Django 4.1.5 on 2024-04-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0019_othercandidates_failed_othercandidates_inserted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='othercandidates',
            name='sent',
        ),
        migrations.AddField(
            model_name='othercandidates',
            name='queued',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
