# Generated by Django 4.1.5 on 2024-06-03 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job_posting', '0020_remove_othercandidates_sent_othercandidates_queued'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPostingLabelWeight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Job Posting Label Weight ID')),
                ('type', models.CharField(choices=[('future_title', 'future_title'), ('recent_title', 'recent_title'), ('recent_skip_title', 'recent_skip_title'), ('exists_anywhere', 'exists_anywhere'), ('summary', 'summary')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='job_posting_label_weight_created_by', to=settings.AUTH_USER_MODEL)),
                ('job_posting_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_posting.jobposting')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='job_posting_label_weight_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'job_posting_label_weight',
            },
        ),
    ]
