# Generated by Django 4.1.5 on 2024-06-03 09:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0021_jobpostinglabelweight'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostinglabelweight',
            name='weightage',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
