# Generated by Django 4.1.5 on 2024-06-03 09:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0022_jobpostinglabelweight_weightage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpostinglabelweight',
            name='weightage',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
