# Generated by Django 4.1.5 on 2024-06-05 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0023_alter_jobpostinglabelweight_weightage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobpostinglabelweight',
            unique_together={('type', 'job_posting_id')},
        ),
    ]
