# Generated by Django 4.1.5 on 2025-03-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0024_alter_jobpostinglabelweight_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='job_industry',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
