# Generated by Django 4.1.5 on 2024-04-10 06:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job_posting', '0020_remove_othercandidates_sent_othercandidates_queued'),
        ('conversation_thread', '0002_alter_conversationthread_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conversationthread',
            unique_together={('candidate_user_id', 'job_posting_id')},
        ),
    ]
