# Generated by Django 4.1.5 on 2024-04-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation_thread', '0003_alter_conversationthread_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='threadmessage',
            name='type',
            field=models.CharField(default='general', max_length=100),
        ),
    ]
