# Generated by Django 4.1.5 on 2024-05-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation_thread', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadmessage',
            name='is_alerted',
            field=models.BooleanField(default=False),
        ),
    ]
