# Generated by Django 4.1.5 on 2023-02-14 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Background Job Id')),
                ('key', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('in_progress', 'in_progress'), ('failed', 'failed'), ('partial_success', 'partial_success'), ('success', 'success')], max_length=300)),
                ('inserted_count', models.BigIntegerField(blank=True, null=True)),
                ('updated_count', models.BigIntegerField(blank=True, null=True)),
                ('failed_count', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='job_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='job_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'background_job',
            },
        ),
        migrations.CreateModel(
            name='ApolloJobs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Apollo Job Id')),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('apollo_job', models.CharField(blank=True, max_length=255, null=True)),
                ('page_number', models.BigIntegerField(blank=True, null=True)),
                ('fetch_limit', models.BigIntegerField(blank=True, null=True)),
                ('frequency', models.CharField(blank=True, choices=[('day', 'day'), ('week', 'week'), ('month', 'month')], max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'pending'), ('in_progress', 'in_progress'), ('failed', 'failed'), ('partial_success', 'partial_success'), ('success', 'success')], max_length=300, null=True)),
                ('apollo_api_query', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='apollo_job_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='apollo_job_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'apollo_jobs',
            },
        ),
        migrations.CreateModel(
            name='ApolloJobRecords',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Apollo Job Record Id')),
                ('records_inserted', models.BigIntegerField(blank=True, null=True)),
                ('records_updated', models.BigIntegerField(blank=True, null=True)),
                ('records_failed', models.BigIntegerField(blank=True, null=True)),
                ('exception_logfile_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apollo_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='celery_jobs.apollojobs')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='apollo_job_record_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='apollo_job_record_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'apollo_job_records',
            },
        ),
    ]
