# Generated by Django 4.1.5 on 2023-02-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celery_jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apollojobs',
            old_name='apollo_api_query',
            new_name='apollo_api_titles',
        ),
        migrations.AddField(
            model_name='apollojobs',
            name='apollo_api_locations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apollojobs',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('in_progress', 'in_progress'), ('failed', 'failed'), ('paused', 'paused'), ('partial_success', 'partial_success'), ('success', 'success')], max_length=300, null=True),
        ),
    ]
