# Generated by Django 4.1.5 on 2023-05-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celery_jobs', '0002_rename_apollo_api_query_apollojobs_apollo_api_titles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apollojobs',
            name='apollo_account_label_ids',
            field=models.TextField(blank=True, null=True),
        ),
    ]
