# Generated by Django 4.1.5 on 2025-03-24 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celery_jobs', '0004_apollojobs_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apollojobs',
            name='job',
        ),
    ]
