# Generated by Django 4.1.5 on 2025-03-31 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0025_jobposting_job_industry'),
        ('celery_jobs', '0005_remove_apollojobs_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='apollojobs',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='job_posting.jobposting'),
        ),
    ]
