# Generated by Django 4.1.5 on 2023-06-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_resumes'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='staged',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
