# Generated by Django 4.1.5 on 2023-06-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_candidate_staged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='staged',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
