# Generated by Django 4.1.5 on 2023-07-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0005_alter_candidate_staged'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='processed_by_extension',
            field=models.BooleanField(default=False),
        ),
    ]
