# Generated by Django 4.1.5 on 2023-07-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0006_candidate_processed_by_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='staged',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
