# Generated by Django 4.1.5 on 2023-09-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0007_alter_candidate_staged'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='credentials',
            field=models.TextField(blank=True, null=True),
        ),
    ]
