# Generated by Django 4.1.5 on 2023-09-07 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidate', '0009_candidate_deleted_at_candidateattributes_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='candidateattributes',
            name='candidate_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate'),
        ),
        migrations.AlterField(
            model_name='candidateeducationhistory',
            name='candidate_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate'),
        ),
        migrations.AlterField(
            model_name='candidateskill',
            name='candidate_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate'),
        ),
        migrations.AlterField(
            model_name='candidateworkhistory',
            name='candidate_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate'),
        ),
        migrations.AlterField(
            model_name='resumes',
            name='candidate_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate'),
        ),
    ]
