# Generated by Django 4.1.5 on 2023-11-23 13:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0011_alter_candidateskill_skill_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateExternalId',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Candidate External Reference Id')),
                ('external_id', models.CharField(max_length=255)),
                ('system', models.CharField(max_length=100)),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate')),
            ],
            options={
                'db_table': 'candidate_external_id',
            },
        ),
    ]
