# Generated by Django 4.1.5 on 2023-12-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0012_candidateexternalid'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='ai_candidate_id',
            field=models.UUIDField(editable=False, null=True, verbose_name='AI Generated Candidate ID'),
        ),
    ]
