# Generated by Django 4.1.5 on 2024-01-19 12:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0016_jobpostingtemplate_company_id'),
        ('candidate', '0013_candidate_ai_candidate_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidateexternalid',
            old_name='external_id',
            new_name='value',
        ),
        migrations.AddField(
            model_name='candidateexternalid',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True),
        ),
        migrations.CreateModel(
            name='ATSCandidates',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ATS Candidate Id')),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate')),
                ('job_posting_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_posting.jobposting')),
            ],
            options={
                'db_table': 'ats_candidates',
            },
        ),
    ]
