# Generated by Django 4.1.5 on 2024-01-22 12:30

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0014_rename_external_id_candidateexternalid_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
