# Generated by Django 4.1.5 on 2024-02-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0015_alter_candidate_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='business_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
