# Generated by Django 4.1.5 on 2024-04-25 09:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0020_remove_othercandidates_sent_othercandidates_queued'),
        ('candidate', '0016_candidate_business_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnmaskedCandidateJobPosting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Unmasked Candidate Job Posting Id')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate')),
                ('job_posting_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_posting.jobposting')),
            ],
            options={
                'db_table': 'unmasked_candidate_job_posting',
            },
        ),
        migrations.CreateModel(
            name='CandidateMaskSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Candidate Mask Settings Id')),
                ('name', models.BooleanField(default=False)),
                ('current_company', models.BooleanField(default=False)),
                ('current_title', models.BooleanField(default=False)),
                ('video_resume', models.BooleanField(default=False)),
                ('resume', models.BooleanField(default=False)),
                ('picture', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate')),
            ],
            options={
                'db_table': 'candidate_mask_settings',
            },
        ),
    ]
