# Generated by Django 4.1.5 on 2024-04-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0017_unmaskedcandidatejobposting_candidatemasksettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatemasksettings',
            name='contact',
            field=models.BooleanField(default=False),
        ),
    ]
