# Generated by Django 4.1.5 on 2024-04-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0018_candidatemasksettings_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatemasksettings',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
