# Generated by Django 4.1.5 on 2024-06-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0019_candidatemasksettings_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumes',
            name='key',
            field=models.TextField(),
        ),
    ]
