# Generated by Django 4.1.5 on 2025-03-12 11:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0020_alter_resumes_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='ai_candidate_id',
            field=models.UUIDField(db_index=True, editable=False, null=True, verbose_name='AI Generated Candidate ID'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Candidate ID'),
        ),
    ]
