# Generated by Django 4.1.5 on 2023-05-03 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_history', '0003_payment_history_currency_payment_history_invoice_id_and_more'),
        ('company', '0002_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='payment_history_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='payment_history.payment_history'),
        ),
    ]
