# Generated by Django 4.1.5 on 2023-05-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_subscription_payment_history_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='reveals_left',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
