# Generated by Django 4.1.5 on 2023-05-22 10:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_resumes'),
        ('company', '0004_subscription_is_expired_subscription_reveals_left_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follows',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Follow ID')),
                ('follow_id', models.UUIDField(blank=True, null=True)),
                ('follow_type', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='candidate.candidate')),
            ],
            options={
                'db_table': 'follows',
            },
        ),
    ]
