# Generated by Django 4.1.5 on 2023-07-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_kanbanboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='subscription_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
