# Generated by Django 4.1.5 on 2023-08-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_company_subscription_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='website_url',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
