# Generated by Django 4.1.5 on 2024-01-19 12:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0014_rename_external_id_candidateexternalid_value_and_more'),
        ('company', '0010_alter_follows_candidate_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='candidate_scope',
            field=models.CharField(blank=True, choices=[('all', 'all'), ('self', 'self'), ('others', 'others')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='minimum_reveals',
            field=models.IntegerField(default=15, null=True),
        ),
        migrations.CreateModel(
            name='CompaniesCandidates',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Companies Candidate Id')),
                ('candidate_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate')),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
            options={
                'db_table': 'companies_candidates',
            },
        ),
    ]
