# Generated by Django 4.1.5 on 2024-01-23 12:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_company_candidate_scope_company_minimum_reveals_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Import Stats Id')),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('total_count', models.BigIntegerField(blank=True, null=True)),
                ('inserted', models.BigIntegerField(blank=True, null=True)),
                ('updated', models.BigIntegerField(blank=True, null=True)),
                ('failed', models.BigIntegerField(blank=True, null=True)),
                ('exception_log', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
            options={
                'db_table': 'import_stats',
            },
        ),
    ]
