# Generated by Django 4.1.5 on 2024-01-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_importstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='importstats',
            name='process_log',
            field=models.TextField(blank=True, null=True),
        ),
    ]
