# Generated by Django 4.1.5 on 2024-01-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_importstats_process_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='candidate_scope',
            field=models.CharField(blank=True, choices=[('all', 'all'), ('self', 'self'), ('others', 'others')], default='all', max_length=50, null=True),
        ),
    ]
