# Generated by Django 4.1.5 on 2024-03-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_alter_company_candidate_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='benefits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='business_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='employees',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='values',
            field=models.TextField(blank=True, null=True),
        ),
    ]
