# Generated by Django 4.1.5 on 2025-03-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_company_benefits_company_business_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='full_admin_control',
            field=models.BooleanField(default=False),
        ),
    ]
