# Generated by Django 4.1.5 on 2025-03-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_company_full_admin_control'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='full_admin_control',
            field=models.BooleanField(default=True),
        ),
    ]
