# Generated by Django 4.1.5 on 2025-03-24 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_alter_company_full_admin_control'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='full_admin_control',
        ),
    ]
