# Generated by Django 4.1.5 on 2025-04-16 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_remove_company_full_admin_control'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='candidate_scope',
            field=models.CharField(blank=True, choices=[('all', 'all'), ('self', 'self'), ('others', 'others')], default='self', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='minimum_reveals',
            field=models.IntegerField(default=25, null=True),
        ),
    ]
