# Generated by Django 4.1.5 on 2023-05-03 12:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment_history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_history',
            name='uuid_id',
            field=models.UUIDField(verbose_name='Payment History Id', default=uuid.uuid4, editable=False),
            preserve_default=False,
        ),
        migrations.RemoveField(model_name='payment_history', name='id'),
        migrations.RenameField(model_name='payment_history', old_name='uuid_id', new_name='id'),
    ]