# Generated by Django 4.1.5 on 2023-05-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_history', '0003_payment_history_currency_payment_history_invoice_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_history',
            name='payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment_history',
            name='payment_method_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment_history',
            name='price_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
