# Generated by Django 4.1.5 on 2023-05-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_history', '0004_payment_history_payment_intent_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_history',
            name='invoice_pdf',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment_history',
            name='invoice_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment_history',
            name='receipt_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
