# Generated by Django 4.1.5 on 2023-07-14 07:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment_history', '0005_payment_history_invoice_pdf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeWebHook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Stripe WebHook Event Id')),
                ('event_id', models.TextField(blank=True, null=True)),
                ('event_type', models.TextField(blank=True, null=True)),
                ('key', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'pending'), ('in_progress', 'in_progress'), ('failed', 'failed'), ('success', 'success')], max_length=80, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'stripe_webhook',
            },
        ),
    ]
