# Generated by Django 4.1.5 on 2023-07-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_history', '0006_stripewebhook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripewebhook',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
