# Generated by Django 4.1.5 on 2023-09-07 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_history', '0007_alter_stripewebhook_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_history',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True),
        ),
    ]
