# Generated by Django 4.1.5 on 2023-10-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_history', '0008_payment_history_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_history',
            name='subtotal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment_history',
            name='tax',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
