# Generated by Django 4.1.5 on 2023-08-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_integrationkey_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationkey',
            name='credentials',
            field=models.TextField(null=True),
        ),
    ]
