# Generated by Django 4.1.5 on 2023-09-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_integrationkey_credentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationkey',
            name='type',
            field=models.CharField(choices=[('jazzHR', 'jazzHR'), ('workable', 'workable')], max_length=255, null=True),
        ),
    ]
