# Generated by Django 4.1.5 on 2023-09-08 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_alter_integrationkey_type'),
        ('integrations', '0004_integrationkey_deleted_at_and_more'),
    ]

    operations = [
    ]
