# Generated by Django 4.1.5 on 2023-12-27 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_merge_20230908_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationkey',
            name='type',
            field=models.CharField(choices=[('jazzHR', 'jazzHR'), ('workable', 'workable'), ('poweredBy', 'poweredBy')], max_length=255, null=True),
        ),
    ]
