# Generated by Django 4.1.5 on 2024-01-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_alter_integrationkey_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationkey',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
