# Generated by Django 4.1.5 on 2023-03-23 09:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job_posting', '0002_jobpostingcandidate_jobpostingcandidateskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLProcess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ML Process Id')),
                ('prescreen_candidates_input', models.TextField()),
                ('job_description_input', models.TextField()),
                ('status', models.CharField(blank=True, choices=[('processed', 'processed'), ('unprocessed', 'unprocessed')], max_length=100, null=True)),
                ('ml_output', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_posting_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='job_posting.jobposting')),
            ],
            options={
                'db_table': 'ml_process',
            },
        ),
    ]
