# Generated by Django 4.1.5 on 2023-04-06 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_alter_candidate_status'),
        ('job_posting', '0002_jobpostingcandidate_jobpostingcandidateskill'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('machine_learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLTrainingData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ML Training Rank Id')),
                ('rank', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='candidate.candidate')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='training_data_created_by', to=settings.AUTH_USER_MODEL)),
                ('job_posting_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='job_posting.jobposting')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='training_data_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ml_training_data',
            },
        ),
    ]
