# Generated by Django 4.1.5 on 2023-06-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0002_mltrainingdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlprocess',
            name='job_posting_candidate_count',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mlprocess',
            name='job_description_input',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mlprocess',
            name='prescreen_candidates_input',
            field=models.TextField(blank=True, null=True),
        ),
    ]
