# Generated by Django 4.1.5 on 2023-09-07 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0008_alter_jobposting_location_id_and_more'),
        ('candidate', '0011_alter_candidateskill_skill_id_and_more'),
        ('machine_learning', '0003_mlprocess_job_posting_candidate_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mltrainingdata',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='mltrainingdata',
            name='candidate_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='candidate.candidate'),
        ),
        migrations.AlterField(
            model_name='mltrainingdata',
            name='job_posting_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_posting.jobposting'),
        ),
    ]
