# Generated by Django 4.1.5 on 2023-12-26 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0004_mltrainingdata_deleted_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mltrainingdata',
            old_name='rank',
            new_name='target_label',
        ),
    ]
