# Generated by Django 4.1.5 on 2024-01-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0005_rename_rank_mltrainingdata_target_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mltrainingdata',
            name='target_label',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
