# Generated by Django 4.1.5 on 2025-03-18 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0006_alter_mltrainingdata_target_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlprocess',
            name='required_candidates',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
