# Generated by Django 4.1.5 on 2025-03-24 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine_learning', '0007_mlprocess_required_candidates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlprocess',
            name='required_candidates',
        ),
    ]
