# Generated by Django 4.1.5 on 2023-08-21 06:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job_posting', '0006_jobposting_remote_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdwerkUnsubscribe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Adwerk Unsubscribe Record Id')),
                ('unsubscribe_email', models.EmailField(max_length=254)),
                ('unsubscribe_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'adwerk_unsubscribe_records',
            },
        ),
        migrations.CreateModel(
            name='AdwerkMailRecords',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Adwerk Mail Record Id')),
                ('sent_from', models.EmailField(max_length=254)),
                ('sent_to', models.EmailField(max_length=254)),
                ('subject', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=255)),
                ('send_at', models.DateTimeField()),
                ('follow_up', models.IntegerField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_posting_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='job_posting.jobposting')),
            ],
            options={
                'db_table': 'adwerk_mail_records',
            },
        ),
    ]