# Generated by Django 4.1.5 on 2023-09-07 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0007_jobposting_deleted_at_jobpostingcandidate_deleted_at_and_more'),
        ('adwerks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adwerkmailrecords',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='adwerkmailrecords',
            name='job_posting_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_posting.jobposting'),
        ),
    ]
