# Generated by Django 4.1.5 on 2023-10-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adwerks', '0002_adwerkmailrecords_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adwerkmailrecords',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
