# Generated by Django 4.1.5 on 2024-05-28 07:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Job Title ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'job_title',
            },
        ),
        migrations.CreateModel(
            name='JobTitleMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Job Title Mapping ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_title', to='title_mapping.jobtitle')),
                ('to_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_title', to='title_mapping.jobtitle')),
            ],
            options={
                'db_table': 'job_title_mapping',
                'unique_together': {('from_title', 'to_title')},
            },
        ),
    ]
