"""
Django settings for startdate project.

Generated by 'django-admin startproject' using Django 4.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
from datetime import timedelta
from pathlib import Path
from decouple import config
from rest_framework.settings import api_settings
from azure.communication.email import EmailClient

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-n2%d2-hu)g4822_l3q1(fq$#-56-8%we888%i4e_@*7hm_o61j'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'api-staging.startdate.co',
    'api.startdate.co',
    'stg-playground.startdate.co',
    'playground.startdate.co',
    'stg-poweredby.startdate.co',
    'poweredby.startdate.co',
    'startdt-steering-wheel.streamlit.app',
    'app.publicaccounting.ai',
    'api.publicaccounting.ai',
    'hcm.startdate.co',
    'api.recruitrite.ai',
    'plus.recruitrite.ai',
    'lite.recruitrite.ai',
    'app.recruitrite.ai'
]

CORS_ORIGIN_ALLOW_ALL = False

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://localhost:3001',
    'http://localhost:5174',
    'http://127.0.0.1',
    'https://hcm.startdate.co',
    'https://staging.startdate.co',
    'https://app.startdate.co',
    'https://www.linkedin.com',
    'https://stg-playground.startdate.co',
    'https://playground.startdate.co',
    'https://stg-poweredby.startdate.co',
    'https://poweredby.startdate.co',
    'https://stg-poweredby-app.startdate.co',
    'https://poweredby-app.startdate.co',
    'https://startdt-steering-wheel.streamlit.app',
    'https://consulting.startdate.co',
    'https://app.publicaccounting.ai',
    'https://api.publicaccounting.ai',
    'https://hcm.startdate.co',
    'https://plus.recruitrite.ai',
    'https://lite.recruitrite.ai',
    'https://app.recruitrite.ai'
]

CORS_ORIGIN_WHITELIST = (
    'http://localhost:3000',
    'http://localhost:3001',
    'http://127.0.0.1',
    'https://staging.startdate.co',
    'https://app.startdate.co',
    'https://playground.startdate.co',
    'https://stg-playground.startdate.co',
    'https://stg-poweredby-app.startdate.co',
    'https://poweredby-app.startdate.co',
    'https://startdt-steering-wheel.streamlit.app',
    'https://consulting.startdate.co',
    'https://app.publicaccounting.ai',
    'https://api.publicaccounting.ai',
    'https://hcm.startdate.co',
    'https://plus.recruitrite.ai',
    'https://lite.recruitrite.ai',
    'https://app.recruitrite.ai'
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_celery_beat',
    'corsheaders',
    'softdelete',
    'knox',
    'accounts',
    'candidate',
    'company',
    'job_posting',
    'celery_jobs',
    'payment_history',
    'machine_learning',
    'adwerks',
    'location',
    'integrations',
    'genai_profile',
    'powered_by',
    'playground',
    'model_training',
    'shareable_link',
    'conversation_thread',
    'filters',
    'title_mapping'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'startdate.middleware.http_404.Custom404MiddleWare',
]

ROOT_URLCONF = 'startdate.urls'
DOMAIN = config("DOMAIN")

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['adwerks/Templates', 'accounts/Templates', 'machine_learning/Templates', 'payment_history/Templates', 'job_posting/Templates', 'candidate/Templates','model_training/Templates', 'shareable_link/Templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'startdate.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config("DB_NAME"),
        'USER': config("DB_USER"),
        'PASSWORD': config("DB_PASSWORD"),
        'HOST': config("DB_HOST"),
        "PORT": 5432,
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Inbuilt USER Model will refer to Custom User Model in Accounts
AUTH_USER_MODEL = 'accounts.User'
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_USERNAME_REQUIRED = False

# CELERY SETTINGS
CELERY_BROKER_URL = config("CELERY_BROKER_URL")
CELERY_RESULT_BACKEND = config("CELERY_RESULT_BACKEND")
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ENABLE_UTC = True
# CELERY_TIMEZONE = 'Asia/Kolkata'
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

REDIS_HOST = config("REDIS_HOST")
REDIS_PORT = 6379

# AWS KEYS
AWS_ACCESS_KEY_ID = config("S3_ACCESS_KEY")
AWS_SECRET_ACCESS_KEY = config("S3_SECRET_KEY")
AWS_STORAGE_BUCKET_NAME = 'startdate-imports-1'
AWS_PROFILE_PICTURE_STORAGE_BUCKET_NAME = 'startdate-images-1'
AWS_RESUME_STORAGE_BUCKET_NAME = 'startdate-resumes-1'
AWS_TRIGGER_EVENTS_BUCKET_NAME = 'startdate-trigger-events-1'


#EMAIL
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'email-smtp.us-east-1.amazonaws.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'AKIAZDZTCEFF2LFUNBM2'
EMAIL_HOST_PASSWORD = 'BG/o/WxTUL3VLm6V3tpZXlFBeEgfgjfamCBPEY4yqaK7'
EMAIL_CLIENT = EmailClient.from_connection_string(config("AZURE_STORAGE_CONNECTION_STRING"))


# APOLLO IO API KEY
APOLLOIO_API_KEY = config("APOLLOIO_API_KEY")
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'knox.auth.TokenAuthentication',
     ),
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.JSONParser',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '5/day',
        'user': '500/day'
    }
}

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "startdate_api_cache_table",
    }
}


REST_KNOX = {
    'SECURE_HASH_ALGORITHM': 'cryptography.hazmat.primitives.hashes.SHA512',
    'AUTH_TOKEN_CHARACTER_LENGTH': 64,
    'TOKEN_TTL': timedelta(hours=24),
    'USER_SERIALIZER': 'knox.serializers.UserSerializer',
    'TOKEN_LIMIT_PER_USER': None,
    'AUTO_REFRESH': True,
    'MIN_REFRESH_INTERVAL': 60,
    'EXPIRY_DATETIME_FORMAT': api_settings.DATETIME_FORMAT,
}

# STRIPE SECRET KEY
STRIPE_SECRET_KEY = config("STRIPE_SECRET_KEY")
STRIPE_WEBHOOK_SECRET = config("STRIPE_WEBHOOK_SECRET")
AI_GOLD_SUBSCRIPTION_PRICE_ID = config("AI_GOLD_SUBSCRIPTION_PRICE_ID")
AI_SILVER_SUBSCRIPTION_PRICE_ID = config("AI_SILVER_SUBSCRIPTION_PRICE_ID")
AI_GOLD_SUBSCRIPTION_REVEALS = int(config("AI_GOLD_SUBSCRIPTION_REVEALS"))
AI_SILVER_SUBSCRIPTION_REVEALS = int(config("AI_SILVER_SUBSCRIPTION_REVEALS"))
FREE_SUBSCRIPTION_REVEALS = int(config("FREE_SUBSCRIPTION_REVEALS"))
STARTER_SCREENING_RECORDS = int(config("STARTER_SCREENING_RECORDS"))
SILVER_SCREENING_RECORDS = int(config("SILVER_SCREENING_RECORDS"))
GOLD_SCREENING_RECORDS = int(config("GOLD_SCREENING_RECORDS"))
PLATINUM_SCREENING_RECORDS = int(config("PLATINUM_SCREENING_RECORDS"))

SOFTDELETE_CASCADE_ALLOW_DELETE_ALL = True

# Cookie domains
STARTDATE_DOMAIN = 'startdate.co'
PUBLIC_ACCOUNTING_DOMAI = 'publicaccounting.ai'
RECRUITRITE_DOMAIN = '.recruitrite.ai'

SESSION_COOKIE_DOMAIN = "recruitrite.ai"  
SESSION_COOKIE_NAME = "sessionid"
SESSION_COOKIE_SECURE = True  
SESSION_COOKIE_HTTPONLY = True  
SESSION_COOKIE_SAMESITE = "None"  
CSRF_COOKIE_DOMAIN = "recruitrite.ai"
CSRF_COOKIE_SECURE = True
CSRF_COOKIE_SAMESITE = "None"